steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "asia-southeast2-docker.pkg.dev/belajar-penerapan-ml-443607/ml-repo/submission-asclepius-api"
      - "."

  # Step 2: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "asia-southeast2-docker.pkg.dev/belajar-penerapan-ml-443607/ml-repo/submission-asclepius-api"

  # Step 3: Deploy the image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "gcloud"
      - "run"
      - "deploy"
      - "submission-asclepius-api"
      - "--image"
      - "asia-southeast2-docker.pkg.dev/belajar-penerapan-ml-443607/ml-repo/submission-asclepius-api"
      - "--platform"
      - "managed"
      - "--region"
      - "asia-southeast2"
      - "--allow-unauthenticated"

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "asia-southeast2-docker.pkg.dev/belajar-penerapan-ml-443607/ml-repo/submission-asclepius-api"
